---
title: "Estatística e probabilidade"
author: "Marcos Ferreira"
date: "`r format(Sys.time(), '%d %B,%Y')`"
output:
  html_document:
    highlight: textmate
    theme: flatly
    toc: yes
    toc_float:
      collapsed: yes
      smooth_srcoll: yes
subtitle: "Aula 1"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE)
```
```{r Pacotes,message=FALSE,warning=FALSE,include=FALSE}
library(dplyr)
library(car)
library(rstatix)
library(emmeans)
library(ggplot2)
library(knitr)
library(kableExtra)
library(htmltools)
```



## **Exemplo 1**. Produção brasileira de óleo de dende 1987-92

```{r oleo de dende}
# Atribuindo  valores  as variáveis
quantidade  <- c(39.3, 39.1, 53.9, 65.1, 69.1,  59.5)
anos  <- c(1987, 1988, 1989, 1990, 1991,  1992)
# Plotando o gráfico de  linhas  individuais
plot(quantidade~anos,
     type = "lines",
     col = "red",
     xlab = "Anos",
     ylab = "Quantidade (1000 t)")
```

## **Exemplo 2**. Produção brasileira de carvão mineral de 1989-92

```{r carregando csv}
# Lendo o arquivo csv
producao_carvao  <- read.csv("producao_carvao.csv")
```
```{r tabela exemplo 2,echo=FALSE}
kable(producao_carvao,col.names = c("Anos","Quantidade  produzida (1000 t)")) %>%
  kable_styling(full_width = FALSE,bootstrap_options = c("striped","hover","condensed","responsive"))
```
```{r carvao mineral}
# Atribuindo valores as variáveis
quantidade2 <- producao_carvao$quatidade
anos2 <- producao_carvao$anos
# Plotando o gráfico de  barras  verticais
barplot(quantidade2,
        names.arg = anos2,
        col = "darkblue",
        xlab = "Anos",
        ylab = "Quantidade  produzida (1000 t)",
        border = "white")

barplot(quantidade2,
        names.arg = anos2,
        col = "darkblue",
        xlab = "Quantidade  produzida (1000 t)",
        ylab = "Anos",
        border = "white",
        horiz = TRUE)

```


## **Exemplo 3.**  Intenção de atividades no feriado prolongado

```{r intenção de atividades no feriado}
# Lendo o arquivo csv
atividades  <- read.csv("atividades_no_feriado.csv")
```
```{r,echo=FALSE}
kable(atividades, col.names = c("Intenção","Número de pessoas")) %>%
  kable_styling(full_width = FALSE,bootstrap_options = c("striped","hover","condensed","responsive"))
```

```{r intenção de atividades no feriado 2}
# Atribuindo valores as variáveis
numero_de_pessoas <- atividades$No_de_pessoas
# Criando rótulos
porcentagens <- round(numero_de_pessoas/sum(numero_de_pessoas)*100)
rotulos <- c("Descansar em casa","Viajar","Passear na própria cidade","Trabalhar")
rotulos <- paste(rotulos,porcentagens)
rotulos <- paste(rotulos,"%")
# Plotando o gráfico em setores
pie(numero_de_pessoas,
    labels = rotulos,
    col = rainbow(5),
    border = FALSE,
    clockwise = TRUE)
```
